### ISSUE TITLE
Enhancement Memory Control

### ISSUE THREAD

**Issue by wbadyx** [OpenGene/defq#1]
When I extract the fq.gz from size 30G data(fq.gz), the memory will be large, was killed by the system.

defq.sh: line 2: 95033 Killed                  /Bioinfo/tools/defq --in1 Undetermined_S0_R1_001.fastq.gz -s /Task/OUT/index2.sheet -o /Task/OUT/P5index -f _R1.fastq.gz

15024 fastq  20   0 70.4g  70g 1420 S 2368.2 55.7 456:49.89 defq

**Comment by sfchen** [comment]
Thanks, I will fix it

**Comment by sfchen** [comment]
This is fixed in v0.2.0
